### ISSUE TITLE
Template config.json from environment variables

### ISSUE THREAD

**Issue by gelphick-helyx** [lewjc/CombiLog-Dashboard#12]
First of all, thanks for Combilog. It's a splendid tool and we find it very helpful. Anyway, onto the issue...

The default of localhost within the config.json means that the only way of using this within a local environment is via a docker swarm where configs can be supplied. It would be helpful if the container startup could template the config.json from environment variables supplied either in a docker run or docker-compose

**Comment by lewjc** [comment]
Hey George, no problem. I have an idea for how to fix this, will look at getting something put together to improve this!

**Comment by lewjc** [comment]
Having just checked through the branches, there is feature/react-dynamic-config-env which should actually resolve this issue.. will look to get it merged into a new version tomorrow

**Comment by lewjc** [comment]
@gelphick-helyx https://github.com/lewjc/CombiLog-Dashboard/pull/13 contains the relevant fixes

**Comment by lewjc** [comment]
@gelphick-helyx `docker pull lewjc/combilog-dashboard:latest-release-1.5.0` let me know how you get on. If no issues persist ill release a new version 1.5.0 of the dashboard. Feel free to raise any new issues if they come up.
